FROM maven:3.9.9-eclipse-temurin-21-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY . .

RUN chmod +x ./mvnw

EXPOSE 8080

COPY docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]