spring:
  application:
    name: Football Club Manager
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  tomcat:
    max-http-header-size: 65536
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 900000
      refresh-token:
        expiration: 604800000
    frontend:
      url: ${FRONTEND_URL}